const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const { protect, requireAdmin } = require('../middleware/authMiddleware');

// Enforce authentication & Super Admin role authorization on all admin routes
router.use(protect, requireAdmin);

// Platform Overview KPIs & Live Operations
router.get('/overview', adminController.getPlatformOverview);
router.get('/live-operations', adminController.getLiveOperationsData);

// Provider Management & 360°
router.get('/providers', adminController.getAllProviders);
router.get('/providers/:id/360', adminController.getProvider360);
router.patch('/providers/:id/status', adminController.updateProviderStatus);
router.patch('/providers/:id/throttle', adminController.updateProviderThrottle);

// Order Reroute Dispatch & Broadcast Queue
router.post('/orders/:id/reroute', adminController.rerouteOrder);
router.get('/dispatch-requests', adminController.getDispatchRequests);

// Driver Management & 360°
router.get('/drivers', adminController.getAllDrivers);
router.post('/drivers', adminController.createDriver);
router.get('/drivers/:id/360', adminController.getDriver360);
router.patch('/drivers/:id/status', adminController.updateDriverStatus);
router.post('/drivers/:id/assign-order', adminController.assignDriverOrder);

// Driver Forensic KYC Verification
router.get('/drivers/kyc-queue', adminController.getDriverKycQueue);
router.patch('/drivers/kyc/:id/approve', adminController.approveDriverKyc);
router.patch('/drivers/kyc/:id/reject', adminController.rejectDriverKyc);
router.patch('/drivers/kyc/:id/request-fix', adminController.requestFixDriverKyc);

// Active Partners Operational Registry
router.get('/drivers/active-registry', adminController.getActivePartnersRegistry);
router.patch('/drivers/:id/toggle-standby', adminController.toggleDriverStandby);
router.post('/drivers/broadcast-announcement', adminController.broadcastDriverAnnouncement);
router.post('/drivers/:id/reroute', adminController.rerouteDriverCanister);

// Offline Telemetry & Fleet Heartbeat Surveillance
router.get('/drivers/offline-telemetry', adminController.getOfflineTelemetrySurveillance);
router.post('/drivers/ping-all-offline', adminController.pingOfflineFleet);
router.post('/drivers/:id/send-push', adminController.sendCourierReconnectPush);
router.post('/drivers/:id/release-reservation', adminController.releaseCourierReservation);

// Driver Immutable Audit Ledger & Cryptographic Block Merkle Chain
router.get('/driver-audits', adminController.getDriverAuditLedger);
router.get('/drivers/audit-ledger', adminController.getDriverAuditLedger);
router.post('/driver-audits/verify', adminController.verifyDriverMerkleBlock);
router.post('/driver-audits/auto-generate', adminController.autoGenerateDriverAudit);

// Fleet Operational Telemetry & Analytics Engine
router.get('/fleet-analytics', adminController.getFleetAnalytics);
router.get('/drivers/fleet-analytics', adminController.getFleetAnalytics);

// Customer Management & 360°
router.get('/customers', adminController.getAllCustomers);
router.get('/customers/:id/360', adminController.getCustomer360);
router.patch('/customers/:id/status', adminController.updateCustomerStatus);

// Subscriptions Lifecycle Management
router.get('/subscriptions', adminController.getAllSubscriptions);
router.get('/subscriptions/:id', adminController.getSubscriptionDetails);
router.patch('/subscriptions/:id/pause', adminController.pauseSubscription);
router.patch('/subscriptions/:id/resume', adminController.resumeSubscription);
router.patch('/subscriptions/:id/cancel', adminController.cancelSubscription);
router.patch('/subscriptions/:id/renew', adminController.renewSubscription);

// Order & Delivery Management & 360°
router.get('/orders', adminController.getAllOrders);
router.get('/orders/:id/360', adminController.getOrder360);

// Finance & Settlements
router.get('/finance', adminController.getFinanceOverview);
router.post('/finance/settle-batch', adminController.processWeeklySettlementBatch);
router.post('/finance/payout/:id', adminController.executeProviderPayout);

// Audit Logs
router.get('/audit-logs', adminController.getAuditLogs);

module.exports = router;
