const Driver = require('../models/Driver');
const DriverKyc = require('../models/DriverKyc');
const DriverTelemetry = require('../models/DriverTelemetry');

const SEED_KYC_CANDIDATES = [
  {
    id: 'DP-6201',
    name: 'Vikram Vaghela',
    initials: 'VV',
    age: 28,
    phone: '+91 98240 55190',
    email: 'vikram.v@matrix.in',
    vehicle: 'Hero Deluxe 100cc',
    plate: 'GJ-01-FD-3910',
    submissionDate: '04 Oct 2026',
    submissionTime: '11:20:14 IST',
    attestation: { aadhaar: true, dl: true, rc: true, ins: true },
    bank: { name: 'State Bank of India (SBI)', account: '390281009012', masked: '•••• 9012', ifsc: 'SBIN0001042', branch: 'Paldi Branch', pennyVerified: true, beneficiary: 'VIKRAM B VAGHELA' },
    status: 'READY_APPROVAL',
    statusLabel: 'Ready For Approval',
    statusTone: 'emerald',
    jurisdiction: 'Paldi, Ahmedabad',
    pin: '380007',
    zone: 'AMD-CENTRAL',
    matchConfidence: 98.4,
    livenessScore: 0.984,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCBk5CH2J1RsxevNHcmQJ1wQNbYH4sQA9DDY1c4HpR59Q0Yw5Yt-WMl8wztua0NTWrOySsrXsEGNJ9S-GpjHw_398sEjroHyP-norXIqnxsGE3JVQZoyMpepItB8CKJZIytosNTjywuIjUaR_yntVrXUDgjhTDn01M3jofpvZeTOtXCwHsT1pD3j3JQnVOmramQbicTg8n_nAKaiee5nDPh0PD2jTWFoAul_hc6WzzB9YdlOEn1_b7',
    aadhaarData: {
      refHash: '9481-2840-1920-BOM',
      recordName: 'VIKRAM BHIKHABHAI VAGHELA',
      maskedUid: 'XXXX XXXX 9184',
      dob: '18/06/1998 (28 Yrs)',
      gender: 'MALE',
      address: 'Paldi, Ahmedabad, Gujarat',
      xmlSha: '3c8e...a911'
    },
    dlData: {
      number: 'GJ-01-20180029144',
      vehicleClass: 'LMV / MCWG (Two Wheeler)',
      authority: 'RTO Ahmedabad Sub-West',
      expiry: '14 Aug 2038 (Active)',
      scanConfidence: '99.2%',
      flag: null,
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfLepWGwe0LpPgS8Ic9UUiYPecOPtXtIwwFtjUAMnBozq_lrHa86NCPzgJF1DrkWYKWJZt3onr474sABecST6qTJTBRwSuY_zmunMsqFAjE1s8Xx-r60ulYuHVIGXIZCPgaaqSmLZsQD_rQBpyQkLvF9E3N-cOwwLDy5qWYDXDAKFW2KgVsOZXz5Gf9oP6yhalPuoWKqFKmZ7MCg1A-BnoH0HeL69ihqQZUZpclbeRMc0PLyUXsDjG'
    },
    rcData: {
      plate: 'GJ-01-FD-3910',
      model: 'Hero MotoCorp Deluxe 100cc',
      chassis: 'MBHJA...8912 / JA05...110',
      emission: 'Bharat Stage VI (BS-VI)',
      fitness: '22 May 2035',
      fuel: 'Petrol',
      owner: 'VIKRAM BHIKHABHAI VAGHELA (1st)'
    },
    insData: {
      provider: 'HDFC ERGO General Insurance',
      policyNo: '#HDFC-ERGO-99219482',
      coverage: 'Comprehensive + 3rd Party Commercial',
      expiry: '24 Sep 2027',
      token: '0x82f0...d29'
    }
  },
  {
    id: 'DP-4409',
    name: 'Rahul Patel',
    initials: 'RP',
    age: 27,
    phone: '+91 98251 44102',
    email: 'rahul.patel@gmail.com',
    vehicle: 'Hero Splendor+ BS-VI',
    plate: 'GJ-01-ET-4819',
    submissionDate: '05 Oct 2026',
    submissionTime: '10:24:19 IST',
    attestation: { aadhaar: true, dl: false, rc: true, ins: true },
    bank: { name: 'HDFC Bank', account: '501004814410', masked: '•••• 4410', ifsc: 'HDFC0001024', branch: 'Bodakdev, Ahmedabad', pennyVerified: true, beneficiary: 'RAHUL V PATEL' },
    status: 'CORRECTION_NEEDED',
    statusLabel: 'Action Required: DL Blur',
    statusTone: 'amber',
    jurisdiction: 'Bodakdev, SG Highway',
    pin: '380054',
    zone: 'AMD-WEST',
    matchConfidence: 94.2,
    livenessScore: 0.984,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAl2nVecQFPSEap4TRVYkiWdY9KpluEDn4k41acpOVJ4xejNf5sPVHAK1wgcHGGplZUmGj2f9kCPvQSqqEYe6FhF0eAOufDS2gZsU2cQAFSh3Qu0YXqF-Qmgbf1ke21eO8wzOoCPWUgjB_rGfxKCC-St0JGB-NsniIuagRW_jbK6S-rccYDiOd6LWVNetPZvZZmqhrclOis419ILRdTbVc9pDNplD1PMXjv_ehanSCubzhfX7XOOPVZ',
    aadhaarData: {
      refHash: '3e7c8f9b...a102',
      recordName: 'RAHUL VINODRAY PATEL',
      maskedUid: 'XXXX XXXX 8912',
      dob: '14/08/1999 (27 Yrs)',
      gender: 'MALE',
      address: 'Bodakdev, Ahmedabad, Gujarat',
      xmlSha: '7f91...b820'
    },
    dlData: {
      number: 'GJ-01-20180049102',
      vehicleClass: 'MCWG / LMV',
      authority: 'RTO Ahmedabad West',
      expiry: '12 Aug 2038',
      scanConfidence: '78.4% (Corner Glare)',
      flag: 'DL BLUR',
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBF-2I-xLbuLe47c3IykFS2y1eal1hx0dgGy7romfyrAy0pFDs3t-5TvLcf40STGKiGvA8MQBUrBMH8hNkYtaWk2AIMNzfvd4TA_pvK1rMuWpPyAKwA4zYoMJp74IdP8PDDHgjno96Lxo-CbOESoYVRv7PhSbf3RBB_F0BcNaMTXXpERFuiEJC37dvr482xYg0AkEUIevsTQI6g8ucFRaavihW1KhDIDhW4r9Rb58gFC556kcSp80_T'
    },
    rcData: {
      plate: 'GJ-01-ET-4819',
      model: 'Hero Splendor+ BS-VI',
      chassis: 'MBHJA...4819 / JA05...392',
      emission: 'Bharat Stage VI',
      fitness: '18 Nov 2036',
      fuel: 'Petrol',
      owner: 'RAHUL V. PATEL (1st)'
    },
    insData: {
      provider: 'HDFC ERGO General',
      policyNo: '#HDFC-ERGO-99219482',
      coverage: 'Comprehensive Third-Party',
      expiry: '19 Sep 2027',
      token: '0x32a1...f01'
    }
  },
  {
    id: 'DP-6202',
    name: 'Sandeep Solanki',
    initials: 'SS',
    age: 31,
    phone: '+91 99042 88123',
    email: 'sandeep.s@gmail.com',
    vehicle: 'Honda Activa 6G',
    plate: 'GJ-01-KZ-7721',
    submissionDate: '04 Oct 2026',
    submissionTime: '14:15:02 IST',
    attestation: { aadhaar: true, dl: false, rc: true, ins: false },
    bank: { name: 'HDFC Bank', account: '501002911120', masked: '•••• 1120', ifsc: 'HDFC0000048', branch: 'Vastrapur, Ahmedabad', pennyVerified: true, beneficiary: 'SANDEEP M SOLANKI' },
    status: 'CORRECTION_NEEDED',
    statusLabel: 'Correction Needed (DL + Ins)',
    statusTone: 'amber',
    jurisdiction: 'Vastrapur, Ahmedabad',
    pin: '380015',
    zone: 'AMD-WEST',
    matchConfidence: 89.2,
    livenessScore: 0.941,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCBk5CH2J1RsxevNHcmQJ1wQNbYH4sQA9DDY1c4HpR59Q0Yw5Yt-WMl8wztua0NTWrOySsrXsEGNJ9S-GpjHw_398sEjroHyP-norXIqnxsGE3JVQZoyMpepItB8CKJZIytosNTjywuIjUaR_yntVrXUDgjhTDn01M3jofpvZeTOtXCwHsT1pD3j3JQnVOmramQbicTg8n_nAKaiee5nDPh0PD2jTWFoAul_hc6WzzB9YdlOEn1_b7',
    aadhaarData: {
      refHash: '8821-4190-2201-BOM',
      recordName: 'SANDEEP MANUBHAI SOLANKI',
      maskedUid: 'XXXX XXXX 3391',
      dob: '12/11/1995 (31 Yrs)',
      gender: 'MALE',
      address: 'Vastrapur, Ahmedabad',
      xmlSha: '8d2a...1102'
    },
    dlData: {
      number: 'GJ-01-20160039120',
      vehicleClass: 'MCWG',
      authority: 'RTO Ahmedabad Sub-West',
      expiry: '20 Nov 2036',
      scanConfidence: '72.1% (Low Light Blur)',
      flag: 'DL BLUR',
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfLepWGwe0LpPgS8Ic9UUiYPecOPtXtIwwFtjUAMnBozq_lrHa86NCPzgJF1DrkWYKWJZt3onr474sABecST6qTJTBRwSuY_zmunMsqFAjE1s8Xx-r60ulYuHVIGXIZCPgaaqSmLZsQD_rQBpyQkLvF9E3N-cOwwLDy5qWYDXDAKFW2KgVsOZXz5Gf9oP6yhalPuoWKqFKmZ7MCg1A-BnoH0HeL69ihqQZUZpclbeRMc0PLyUXsDjG'
    },
    rcData: {
      plate: 'GJ-01-KZ-7721',
      model: 'Honda Activa 6G',
      chassis: 'ME4JF...7721',
      emission: 'BS-VI',
      fitness: '14 Jan 2036',
      fuel: 'Petrol',
      owner: 'SANDEEP M SOLANKI (1st)'
    },
    insData: {
      provider: 'None / Expired',
      policyNo: 'EXPIRED-2025',
      coverage: 'Policy lapsed',
      expiry: 'Expired (15 Aug 2026)',
      token: 'N/A'
    }
  },
  {
    id: 'DP-6203',
    name: 'Manish Parmar',
    initials: 'MP',
    age: 25,
    phone: '+91 97129 11984',
    email: 'm.parmar99@live.com',
    vehicle: 'TVS Jupiter 110',
    plate: 'GJ-01-NM-4491',
    submissionDate: '03 Oct 2026',
    submissionTime: '19:42:10 IST',
    attestation: { aadhaar: true, dl: true, rc: true, ins: true },
    bank: { name: 'ICICI Bank', account: '002401544401', masked: '•••• 4401', ifsc: 'ICIC0000024', branch: 'Navrangpura Branch', pennyVerified: true, beneficiary: 'MANISH PARMAR' },
    status: 'READY_APPROVAL',
    statusLabel: 'Ready For Approval',
    statusTone: 'emerald',
    jurisdiction: 'Navrangpura, Ahmedabad',
    pin: '380009',
    zone: 'AMD-CENTRAL',
    matchConfidence: 97.8,
    livenessScore: 0.991,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCBk5CH2J1RsxevNHcmQJ1wQNbYH4sQA9DDY1c4HpR59Q0Yw5Yt-WMl8wztua0NTWrOySsrXsEGNJ9S-GpjHw_398sEjroHyP-norXIqnxsGE3JVQZoyMpepItB8CKJZIytosNTjywuIjUaR_yntVrXUDgjhTDn01M3jofpvZeTOtXCwHsT1pD3j3JQnVOmramQbicTg8n_nAKaiee5nDPh0PD2jTWFoAul_hc6WzzB9YdlOEn1_b7',
    aadhaarData: {
      refHash: '5519-1029-4401-BOM',
      recordName: 'MANISH KIRITBHAI PARMAR',
      maskedUid: 'XXXX XXXX 5521',
      dob: '23/04/2001 (25 Yrs)',
      gender: 'MALE',
      address: 'Navrangpura, Ahmedabad',
      xmlSha: '1a90...df33'
    },
    dlData: {
      number: 'GJ-01-20200019283',
      vehicleClass: 'MCWG',
      authority: 'RTO Ahmedabad Sub-West',
      expiry: '22 Apr 2041 (Active)',
      scanConfidence: '98.7%',
      flag: null,
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfLepWGwe0LpPgS8Ic9UUiYPecOPtXtIwwFtjUAMnBozq_lrHa86NCPzgJF1DrkWYKWJZt3onr474sABecST6qTJTBRwSuY_zmunMsqFAjE1s8Xx-r60ulYuHVIGXIZCPgaaqSmLZsQD_rQBpyQkLvF9E3N-cOwwLDy5qWYDXDAKFW2KgVsOZXz5Gf9oP6yhalPuoWKqFKmZ7MCg1A-BnoH0HeL69ihqQZUZpclbeRMc0PLyUXsDjG'
    },
    rcData: {
      plate: 'GJ-01-NM-4491',
      model: 'TVS Jupiter 110',
      chassis: 'MD626...4491',
      emission: 'BS-VI',
      fitness: '05 Mar 2036',
      fuel: 'Petrol',
      owner: 'MANISH K PARMAR (1st)'
    },
    insData: {
      provider: 'Bajaj Allianz General Insurance',
      policyNo: '#BAGI-2026-904128',
      coverage: 'Comprehensive Commercial',
      expiry: '10 Feb 2028',
      token: '0x71e9...c88'
    }
  },
  {
    id: 'DP-6204',
    name: 'Kunal Rawal',
    initials: 'KR',
    age: 29,
    phone: '+91 98251 00293',
    email: 'kunal.r@outlook.com',
    vehicle: 'Bajaj Platina 110',
    plate: 'GJ-27-AL-0914',
    submissionDate: '03 Oct 2026',
    submissionTime: '10:04:44 IST',
    attestation: { aadhaar: true, dl: false, rc: true, ins: false },
    bank: { name: 'Bank of Baroda (BOB)', account: '04120100007731', masked: '•••• 7731', ifsc: 'BARB0PALDIX', branch: 'Paldi Branch', pennyVerified: true, beneficiary: 'KUNAL RAWAL' },
    status: 'FLAGGED_EXPIRED_DL',
    statusLabel: 'Flagged: Expired DL',
    statusTone: 'red',
    jurisdiction: 'Bopal Junction, Ahmedabad',
    pin: '380058',
    zone: 'AMD-WEST',
    matchConfidence: 82.0,
    livenessScore: 0.912,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCBk5CH2J1RsxevNHcmQJ1wQNbYH4sQA9DDY1c4HpR59Q0Yw5Yt-WMl8wztua0NTWrOySsrXsEGNJ9S-GpjHw_398sEjroHyP-norXIqnxsGE3JVQZoyMpepItB8CKJZIytosNTjywuIjUaR_yntVrXUDgjhTDn01M3jofpvZeTOtXCwHsT1pD3j3JQnVOmramQbicTg8n_nAKaiee5nDPh0PD2jTWFoAul_hc6WzzB9YdlOEn1_b7',
    aadhaarData: {
      refHash: '4019-2910-7731-BOM',
      recordName: 'KUNAL PRAVINBHAI RAWAL',
      maskedUid: 'XXXX XXXX 7719',
      dob: '15/09/1997 (29 Yrs)',
      gender: 'MALE',
      address: 'Bopal, Ahmedabad',
      xmlSha: '9c02...e541'
    },
    dlData: {
      number: 'GJ-27-20150009182',
      vehicleClass: 'MCWG',
      authority: 'RTO Ahmedabad East',
      expiry: '15 Sep 2026 (Expired)',
      scanConfidence: '99.0%',
      flag: 'DL EXPIRED 15-SEP',
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfLepWGwe0LpPgS8Ic9UUiYPecOPtXtIwwFtjUAMnBozq_lrHa86NCPzgJF1DrkWYKWJZt3onr474sABecST6qTJTBRwSuY_zmunMsqFAjE1s8Xx-r60ulYuHVIGXIZCPgaaqSmLZsQD_rQBpyQkLvF9E3N-cOwwLDy5qWYDXDAKFW2KgVsOZXz5Gf9oP6yhalPuoWKqFKmZ7MCg1A-BnoH0HeL69ihqQZUZpclbeRMc0PLyUXsDjG'
    },
    rcData: {
      plate: 'GJ-27-AL-0914',
      model: 'Bajaj Platina 110',
      chassis: 'MD2A5...0914',
      emission: 'BS-IV',
      fitness: '12 Aug 2031',
      fuel: 'Petrol',
      owner: 'KUNAL P RAWAL (1st)'
    },
    insData: {
      provider: 'United India Insurance',
      policyNo: 'UII-2024-91024',
      coverage: '3rd Party Only',
      expiry: 'Expired (2025)',
      token: 'N/A'
    }
  },
  {
    id: 'DP-6205',
    name: 'Hardik Barot',
    initials: 'HB',
    age: 22,
    phone: '+91 99982 77412',
    email: 'hardik.b22@gmail.com',
    vehicle: 'Hero Splendor+',
    plate: 'GJ-01-QQ-5109',
    submissionDate: '02 Oct 2026',
    submissionTime: '08:14:50 IST',
    attestation: { aadhaar: false, dl: false, rc: false, ins: false },
    bank: { name: 'Axis Bank', account: '918020003049', masked: '•••• 3049', ifsc: 'UTIB0000102', branch: 'Satellite Branch', pennyVerified: false, beneficiary: 'Awaiting Auth' },
    status: 'INCOMPLETE_KYC',
    statusLabel: 'Incomplete KYC',
    statusTone: 'zinc',
    jurisdiction: 'Satellite, Ahmedabad',
    pin: '380015',
    zone: 'AMD-WEST',
    matchConfidence: 64.0,
    livenessScore: 0.81,
    selfieUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCBk5CH2J1RsxevNHcmQJ1wQNbYH4sQA9DDY1c4HpR59Q0Yw5Yt-WMl8wztua0NTWrOySsrXsEGNJ9S-GpjHw_398sEjroHyP-norXIqnxsGE3JVQZoyMpepItB8CKJZIytosNTjywuIjUaR_yntVrXUDgjhTDn01M3jofpvZeTOtXCwHsT1pD3j3JQnVOmramQbicTg8n_nAKaiee5nDPh0PD2jTWFoAul_hc6WzzB9YdlOEn1_b7',
    aadhaarData: {
      refHash: 'PENDING_OTP',
      recordName: 'HARDIK B BAROT',
      maskedUid: 'XXXX XXXX 1109',
      dob: '10/01/2004 (22 Yrs)',
      gender: 'MALE',
      address: 'Satellite, Ahmedabad',
      xmlSha: 'N/A'
    },
    dlData: {
      number: 'UNVERIFIED',
      vehicleClass: 'Pending upload',
      authority: 'RTO Sub-West',
      expiry: 'Pending',
      scanConfidence: 'N/A',
      flag: 'DL UNVERIFIED',
      scanUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfLepWGwe0LpPgS8Ic9UUiYPecOPtXtIwwFtjUAMnBozq_lrHa86NCPzgJF1DrkWYKWJZt3onr474sABecST6qTJTBRwSuY_zmunMsqFAjE1s8Xx-r60ulYuHVIGXIZCPgaaqSmLZsQD_rQBpyQkLvF9E3N-cOwwLDy5qWYDXDAKFW2KgVsOZXz5Gf9oP6yhalPuoWKqFKmZ7MCg1A-BnoH0HeL69ihqQZUZpclbeRMc0PLyUXsDjG'
    },
    rcData: {
      plate: 'GJ-01-QQ-5109',
      model: 'Hero Splendor+',
      chassis: 'MBHJA...5109',
      emission: 'BS-VI',
      fitness: '2038',
      fuel: 'Petrol',
      owner: 'HARDIK B BAROT'
    },
    insData: {
      provider: 'Unverified',
      policyNo: 'N/A',
      coverage: 'Pending review',
      expiry: 'N/A',
      token: 'N/A'
    }
  }
];

const SEED_OFFLINE_COURIERS = [
  {
    id: 'DP-4409',
    name: 'Rahul Verma',
    initials: 'RV',
    device: 'Samsung Galaxy A14 • Jio 4G',
    lastHeartbeatTime: '14:28:10 IST',
    lastHeartbeatAgo: '4m ago',
    inactiveMins: 4,
    inactiveDisplay: '04 mins',
    lastLocationName: 'Bodakdev Hub',
    coords: '23.0384° N, 72.5119° E',
    battery: 72,
    batteryIcon: 'battery_5_bar',
    disconnectReasonCode: 'MANUAL',
    disconnectReason: 'Clean Manual App Go-Offline',
    detailNote: 'Completed: #TL-4956',
    phone: '+91 98251 44102',
    isSevered: false,
    severity: 'LOW',
    osStack: 'Android 14 • Stitch v4.21',
    hardware: 'Samsung Galaxy A14 (Jio 5G)',
    tempCore: '32.1°C',
    precision: '±2.4m before disconnect',
    rootCause: 'Courier toggled shift off after completing scheduled lunch run.',
    retryDaemon: [
      { num: 1, time: '14:28:15', status: 'ACK_CLEAN_DISCONNECT' }
    ]
  },
  {
    id: 'DP-3812',
    name: 'Amit Shah',
    initials: 'AS',
    device: 'Redmi Note 12 • Airtel 4G',
    lastHeartbeatTime: '13:44:02 IST',
    lastHeartbeatAgo: '48m ago',
    inactiveMins: 48,
    inactiveDisplay: '48 mins',
    lastLocationName: 'Vastrapur Lake',
    coords: '23.0298° N, 72.5284° E',
    battery: 21,
    batteryIcon: 'battery_2_bar',
    disconnectReasonCode: 'TIMEOUT',
    disconnectReason: 'Socket Timeout (Packet Drop)',
    detailNote: 'Active drop along ring corridor',
    phone: '+91 98980 12044',
    isSevered: true,
    severity: 'MEDIUM',
    osStack: 'Android 13 • Stitch v4.19',
    hardware: 'Xiaomi Redmi Note 12 (Airtel)',
    tempCore: '34.8°C Normal',
    precision: '±14.2m before dropout',
    rootCause: 'Cell Tower Handover Fail at Vastrapur Ring Road Node B-11',
    retryDaemon: [
      { num: 1, time: '13:45:00', status: 'NO_ACK (Timeout 5000ms)' },
      { num: 2, time: '13:46:00', status: 'NO_ACK (WSS Reset)' },
      { num: 3, time: '13:47:00', status: 'CELL_UNREACHABLE' }
    ]
  },
  {
    id: 'DP-1104',
    name: 'Suresh Solanki',
    initials: 'SS',
    device: 'Vivo Y20 • No Carrier Signal',
    lastHeartbeatTime: '12:17:49 IST',
    lastHeartbeatAgo: '2h 15m ago',
    inactiveMins: 135,
    inactiveDisplay: '135 mins',
    lastLocationName: 'Paldi South',
    coords: '23.0112° N, 72.5610° E',
    battery: 6,
    batteryIcon: 'battery_alert',
    disconnectReasonCode: 'BATTERY',
    disconnectReason: 'Battery Depletion / Shutdown',
    detailNote: 'Last voltage reported: 3.2V',
    phone: '+91 99042 18839',
    isSevered: true,
    severity: 'CRITICAL',
    osStack: 'Android 12 • Stitch v3.88',
    hardware: 'Vivo Y20 (Vi 4G)',
    tempCore: '39.4°C High Drain',
    precision: '±28.0m before shutdown',
    rootCause: 'Complete device power loss. Battery fell below critical threshold (<10%).',
    retryDaemon: [
      { num: 1, time: '12:18:00', status: 'DEVICE_POWERED_OFF' },
      { num: 2, time: '12:20:00', status: 'SOCKET_CLOSED_ABRUPT' }
    ]
  },
  {
    id: 'DP-6203',
    name: 'Manish Parmar',
    initials: 'MP',
    device: 'OnePlus Nord • JioFiber WiFi',
    lastHeartbeatTime: '10:52:14 IST',
    lastHeartbeatAgo: '3h 40m ago',
    inactiveMins: 220,
    inactiveDisplay: '220 mins',
    lastLocationName: 'Navrangpura Cross',
    coords: '23.0360° N, 72.5510° E',
    battery: 88,
    batteryIcon: 'battery_6_bar',
    disconnectReasonCode: 'MANUAL',
    disconnectReason: 'End of Lunch Shift Scheduled Off',
    detailNote: 'Scheduled return: 18:30 IST',
    phone: '+91 97129 11984',
    isSevered: false,
    severity: 'LOW',
    osStack: 'Android 14 • Stitch v4.20',
    hardware: 'OnePlus Nord CE3 (Jio)',
    tempCore: '31.2°C',
    precision: '±3.1m',
    rootCause: 'Shift block concluded. Resting in Navrangpura standby hub.',
    retryDaemon: [
      { num: 1, time: '10:52:20', status: 'STANDBY_ACK_OK' }
    ]
  },
  {
    id: 'DP-6202',
    name: 'Sandeep Solanki',
    initials: 'SS',
    device: 'Realme Narzo 50 • Vi 4G',
    lastHeartbeatTime: '09:22:40 IST',
    lastHeartbeatAgo: '5h 10m ago',
    inactiveMins: 310,
    inactiveDisplay: '310 mins',
    lastLocationName: 'Chandkheda Highway',
    coords: '23.1110° N, 72.5890° E',
    battery: 45,
    batteryIcon: 'battery_4_bar',
    disconnectReasonCode: 'GEOFENCE',
    disconnectReason: 'Geofence Exit (Out of Corridor)',
    detailNote: 'Outside Sector Zone B-4',
    phone: '+91 99042 88123',
    isSevered: true,
    severity: 'HIGH',
    osStack: 'Android 13 • Stitch v4.18',
    hardware: 'Realme Narzo 50 (Vi)',
    tempCore: '35.0°C',
    precision: '±8.5m',
    rootCause: 'Courier breached Ahmedabad West Geofence boundary toward Gandhinagar Highway.',
    retryDaemon: [
      { num: 1, time: '09:25:00', status: 'GEOFENCE_BREACH_ALERT' },
      { num: 2, time: '09:30:00', status: 'ROAMING_DROPPED' }
    ]
  },
  {
    id: 'DP-6205',
    name: 'Hardik Barot',
    initials: 'HB',
    device: 'Unknown Hardware • Unbound',
    lastHeartbeatTime: 'Never Connected',
    lastHeartbeatAgo: 'Never Connected',
    inactiveMins: 9999,
    inactiveDisplay: 'N/A',
    lastLocationName: 'Address: Paldi Hub',
    coords: 'No GPS fix recorded',
    battery: 0,
    batteryIcon: 'battery_unknown',
    disconnectReasonCode: 'UNREGISTERED',
    disconnectReason: 'Pending Device Token Auth',
    detailNote: 'KYC Approved 1d ago',
    phone: '+91 99982 77412',
    isSevered: false,
    severity: 'PENDING',
    osStack: 'Unregistered / Awaiting Auth',
    hardware: 'Awaiting first device handshake',
    tempCore: 'N/A',
    precision: 'No Telemetry Available',
    rootCause: 'Driver passed KYC review yesterday but has not yet installed or authenticated the mobile app.',
    retryDaemon: [
      { num: 1, time: 'Initial', status: 'INVITATION_SMS_SENT' }
    ]
  }
];

const SEED_ACTIVE_DRIVERS = [
  {
    driverId: 'TL-4409-B',
    name: 'Rahul Patel',
    phone: '+91 98251 44102',
    email: 'rahul.patel@tiffinlink.com',
    rating: 4.9,
    vehicleNo: 'GJ 01 ET 4819',
    vehicleType: 'Hero Splendor+',
    status: 'BUSY',
    activeDeliveries: 1,
    currentLocation: { lat: 23.0384, lng: 72.5119, address: 'Bodakdev Central, Ahmedabad' },
    cluster: 'Bodakdev Central',
    hubAssociation: 'Ahmedabad West Hub 01'
  },
  {
    driverId: 'TL-3812-B',
    name: 'Amit Shah',
    phone: '+91 98980 12044',
    email: 'amit.shah@tiffinlink.com',
    rating: 4.8,
    vehicleNo: 'GJ 01 WQ 8819',
    vehicleType: 'Honda Activa 6G',
    status: 'AVAILABLE',
    activeDeliveries: 0,
    currentLocation: { lat: 23.0298, lng: 72.5284, address: 'Bodakdev Hub, Ahmedabad' },
    cluster: 'Bodakdev Hub',
    hubAssociation: 'Ahmedabad West Hub 01'
  },
  {
    driverId: 'TL-5102-B',
    name: 'Imran Khan',
    phone: '+91 97129 88341',
    email: 'imran.k@tiffinlink.com',
    rating: 4.9,
    vehicleNo: 'GJ 01 AB 3410',
    vehicleType: 'Bajaj Pulsar 150',
    status: 'BUSY',
    activeDeliveries: 1,
    currentLocation: { lat: 23.0360, lng: 72.5510, address: 'Navrangpura Hub, Ahmedabad' },
    cluster: 'Navrangpura Hub',
    hubAssociation: 'Ahmedabad Central Hub 02'
  },
  {
    driverId: 'TL-2940-B',
    name: 'Jay Patel',
    phone: '+91 99240 19283',
    email: 'jay.p@tiffinlink.com',
    rating: 4.7,
    vehicleNo: 'GJ 01 KL 1928',
    vehicleType: 'TVS Jupiter 110',
    status: 'PAUSED',
    activeDeliveries: 0,
    currentLocation: { lat: 23.0298, lng: 72.5284, address: 'Vastrapur Lake Standby' },
    cluster: 'Vastrapur Lake',
    hubAssociation: 'Ahmedabad West Hub 01'
  },
  {
    driverId: 'TL-1982-B',
    name: 'Hardik Parmar',
    phone: '+91 99251 00293',
    email: 'hardik.p@tiffinlink.com',
    rating: 4.8,
    vehicleNo: 'GJ 01 NM 4491',
    vehicleType: 'Bajaj Platina 110',
    status: 'AVAILABLE',
    activeDeliveries: 0,
    currentLocation: { lat: 23.0112, lng: 72.5610, address: 'Paldi Crossroads, Ahmedabad' },
    cluster: 'Paldi Crossroads',
    hubAssociation: 'Ahmedabad South Hub 03'
  }
// Dummy driver seeding disabled - only genuine database records are loaded
async function ensureSeedData() {
  // Intentionally empty: no mock or dummy records are generated
  return;
}

module.exports = {
  ensureSeedData
};

